name: Build a windows rust image
on: [push, repository_dispatch]

jobs:
  build:
    name: latest_rust
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: rustdesk
          repo: rustdesk
          excludes: prerelease, draft

      - id: output
        run: echo "${{ steps.keydb.outputs.release }}"
