name: Build a windows rust image
on: [push, repository_dispatch]

jobs:
  build:
    name: latest_rust
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: rustdesk
          repo: rustdesk
          excludes: prerelease, draft
      
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "rustdesk/rustdesk"
          latest: true
          fileName: "*-x86_64.exe"

      - id: output
        run: echo "${{ steps.keydb.outputs.release }}"
      - id: list
        run: mv *-x86_64.exe rustdesk-42.exe
      - name: Upload to release

      - id: upload
        uses: JasonEtco/upload-to-release@master
        with:
          args: rustdesk-42.exe
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

